#define W_ON "on"
#define W_OFF "off"
#define W_OK "ok"
#define W_STATE "state"
#define W_FAIL "fail"
#define W_SSID "ssid"
#define W_MQTT "mqtt"
#define W_MQTT_USER "mqtt_usr"
#define W_MQTT_PSW "mqtt_psw"
#define W_MQTT_PREFIX "mqtt_prefix"
#define W_MQTT_INFO "/info"
#define W_PASS "pass"
#define W_NTP "ntp"
#define W_ALWAYS_ON "always_on"
#define W_MAC "mac"
#define W_UPTIME "uptime"
#define W_HEAP "heap"
#define W_RESET_REASON "reset_reason"
#define W_SDK "sdk"
#define W_BUILD "build"
#define W_HOUR "hour"
#define W_MIN "min"
#define W_START "start"
#define W_END "end"
#define W_ENABLED "enabled"
#define W_STATE "state"
#define W_COUNT "count"
#define W_DATETIME "time"
#define W_DESCRIPTION "desc"

#define W_SENSOR_NAME "name"
#define W_SENSOR_ADDR "addr"
#define W_SENSOR_TYPE "type"
#define W_SENSOR_VAL "val"

#define API_HTML_JSON_ARG "json"
#define API_HTML_INDEX_ARG "index"
#define API_RESPOND_TYPE "text/json"
#define API_RESPONSE_TYPE "response_type"
#define API_RESPONSE_TEXT "response_text"
#define API_ERROR_TYPE "error"
#define API_SUCCESS_TYPE "success"

#define PAGE_MAIN "/"
#define PAGE_NETWORK "/network.html"
#define PAGE_SYSTEM "/system.html"
#define PAGE_MQTT "/mqtt.html"
#define API_METHOD_FIRMWARE_UPLOAD "/firmware_upload.do"


#define RESPOND_BUFFER_SIZE 750
